- hosts: 127.0.0.1
  sudo: yes
  gather_facts: no
  tasks:
     - stat:
         path: /path/dspace3
       register: s

     - name: create directory
       file: path=/dspace3 state=directory owner=dspace recurse=yes
       when: s.stat.isdir is not defined

     - name: Fourth Dspace Change dspace installation directory in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: 'dspace.install.dir=/dspace2'
         replace: 'dspace.install.dir=/dspace3'
       when: s.stat.isdir is not defined
    
     - include_vars: spoilers.yml  
     - name: Fourth Dspace Replace database URL in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: '{{dspacedburl2}}'
         replace: '{{dspacedburl3}}'
       when: s.stat.isdir is not defined

     - name: Replace dspace base URL in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: 'dspace.baseUrl = http://localhost:8282'
         replace: 'dspace.baseUrl = http://localhost:8383'
       when: s.stat.isdir is not defined

     - name: Replace solr server in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: 'solr.server=http://localhost:8082/solr'
         replace: 'solr.server=http://localhost:8383/solr'
       when: s.stat.isdir is not defined

     - name: Build the project with maven
       command: mvn -U package chdir=/dspace-source/dspace-5.6-src-release
       ignore_errors: yes
       when: s.stat.isdir is not defined

     - name: Run ant clean install
       command: ant fresh_install chdir=/dspace-source/dspace-5.6-src-release/dspace/target/dspace-installer
       when: s.stat.isdir is not defined
