- hosts: 127.0.0.1
  sudo: yes
  gather_facts: no
  tasks:
     - stat:
         path: /path/dspace4
       register: t

     - name: create directory
       file: path=/dspace4 state=directory owner=dspace recurse=yes
       when: t.stat.isdir is not defined
       
     - name: Second Dspace Change dspace installation directory in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: 'dspace.install.dir=/dspace3'
         replace: 'dspace.install.dir=/dspace4'
       when: t.stat.isdir is not defined

     - include_vars: spoilers.yml
     - name: Fifth Dspace Replace database URL in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: '{{dspacedburl3}}'
         replace: '{{dspacedburl4}}'
       when: t.stat.isdir is not defined

     - name: Replace dspace base URL in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: 'dspace.baseUrl = http://localhost:8383'
         replace: 'dspace.baseUrl = http://localhost:8484'
       when: t.stat.isdir is not defined
   
     - name: Replace solr server in /dspace-source/dspace-5.6-src-release/build.properties
       replace:
         dest: /dspace-source/dspace-5.6-src-release/build.properties
         regexp: 'solr.server=http://localhost:8383/solr'
         replace: 'solr.server=http://localhost:8484/solr'
       when: t.stat.isdir is not defined

     - name: Build the project with maven
       command: mvn -U package chdir=/dspace-source/dspace-5.6-src-release
       ignore_errors: yes
       when: t.stat.isdir is not defined

     - name: Run ant clean install
       command: ant fresh_install chdir=/dspace-source/dspace-5.6-src-release/dspace/target/dspace-installer
       when: t.stat.isdir is not defined
