---
- hosts: 127.0.0.1
  tasks:
     - name: Install Third Tomcat
       file:
         path: /opt/tomcat2
         mode: 0755
         state: directory

     - name: Copies Conf, logs, webapps, temp, work folders
       shell: |
           cp -a /opt/tomcat/conf /opt/tomcat2
           cp -a /opt/tomcat/logs /opt/tomcat2
           cp -a /opt/tomcat/webapps /opt/tomcat2
           cp -a /opt/tomcat/temp /opt/tomcat2
           cp -a /opt/tomcat/work /opt/tomcat2


     - name: Remove PID file from temp
       shell: rm /opt/tomcat2/temp/tomcat.pid
       ignore_errors: yes

     - name: Change Server shutdown port in Server.xml in tomcat2
       replace:
         dest: /opt/tomcat2/conf/server.xml
         regexp: 'Server port="8005"'
         replace: 'Server port="8205"'


     - name: Change HTTP Connector port in tomcat2
       replace:
         dest: /opt/tomcat2/conf/server.xml
         regexp: 'Connector port="8080"'
         replace: 'Connector port="8282"'


     - name: Change AJP connector in tomcat2
       replace:
         dest: /opt/tomcat2/conf/server.xml
         regexp: 'Connector port="8009"'
         replace: 'Connector port="8209"'

     - file:
          path: /opt/startup2.sh
          state: touch
          mode: 0777

     - name: Edits startup2.sh
       blockinfile:
         path: /opt/startup2.sh
         block: |
            #!/bin/bash
            export CATALINA_BASE=/opt/tomcat2
               cd /opt/tomcat/bin
               ./startup.sh

     - file:
          path: /opt/shutdown2.sh
          state: touch
          mode: 0777
          
     - name: Edits Shutdown2.sh
       blockinfile:
         path: /opt/shutdown2.sh
         block: |
            #!/bin/bash
            export CATALINA_BASE=/opt/tomcat2
               cd /opt/tomcat/bin
               ./shutdown.sh

     - file:
          path: /etc/init.d/tomcat2
          state: touch
          mode: 0777

     - name: Inserts Configuration settings into tomcat2.service file
       shell: |
              echo '#!/bin/bash' >> /etc/init.d/tomcat2
              echo  '### BEGIN INIT INFO' >> /etc/init.d/tomcat2
              echo  '# Provides:        tomcat7.2' >> /etc/init.d/tomcat2
              echo  '# Required-Start:  $network' >> /etc/init.d/tomcat2
              echo  '# Required-Stop:   $network' >> /etc/init.d/tomcat2
              echo  '# Default-Start:   2 3 4 5' >> /etc/init.d/tomcat2
              echo  '# Default-Stop:    0 1 6' >> /etc/init.d/tomcat2
              echo  '# Short-Description: Start/Stop Tomcat2 server' >> /etc/init.d/tomcat2
              echo  '### END INIT INFO' >> /etc/init.d/tomcat2
              echo  '' >> /etc/init.d/tomcat2
              echo  'PATH=/sbin:/bin:/usr/sbin:/usr/bin' >> /etc/init.d/tomcat2
              echo  '' >> /etc/init.d/tomcat2
              echo  'start() {' >> /etc/init.d/tomcat2
              echo  ' sh /opt/startup2.sh' >> /etc/init.d/tomcat2
              echo  '}' >> /etc/init.d/tomcat2
              echo  '' >> /etc/init.d/tomcat2
              echo  'stop() {' >> /etc/init.d/tomcat2
              echo  ' sh /opt/shutdown2.sh' >> /etc/init.d/tomcat2
              echo  '}' >> /etc/init.d/tomcat2
              echo  '' >> /etc/init.d/tomcat2
              echo  'case $1 in' >> /etc/init.d/tomcat2
              echo  '  start|stop) $1;;' >> /etc/init.d/tomcat2
              echo  '  restart) stop; start;;' >> /etc/init.d/tomcat2
              echo  '  *) echo "Run as $0 <start|stop|restart>"; exit 1;;' >> /etc/init.d/tomcat2
              echo  'esac' >> /etc/init.d/tomcat2

     - name: Update xmlui.xml file
       replace:
         dest: /opt/tomcat2/conf/Catalina/localhost/xmlui.xml
         regexp:  'docBase="/dspace/webapps/xmlui'
         replace:  'docBase="/dspace2/webapps/xmlui'


     - name: Make tomcat service file executable
       command: chmod +x /etc/init.d/tomcat2

     - name: Update Rc Defaults
       command: update-rc.d tomcat2 defaults

     - name: Starts Tomcat2
       command: service tomcat2 start


     - name: Enables port 8282 through the firewall
       command: ufw allow 8282